# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TSPlayDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  # Pods for TSPlayDemo
  pod "GCDWebServer/WebDAV", "~> 3.0"
  target 'TSPlayDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TSPlayDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
